import type { StructuredOutputValidationEvidence } from "./structured-output-evidence-schema.ts";

const FORBIDDEN = /token|secret|authorization|api[_-]?key|account|https?:\/\/|\/(?:Users|tmp|private|var)\/|prompt|payload|raw|content|result|url|path|identity/iu;
export function sanitizeStructuredOutputEvidence(value: StructuredOutputValidationEvidence): StructuredOutputValidationEvidence {
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value.runId) || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/u.test(value.correlationId) || !["proceed", "reject"].includes(value.result) || !["unavailable", "attested"].includes(value.containment) || value.reproductionCommand !== "npm run validate:structured-output" || FORBIDDEN.test(JSON.stringify(value.stopConditions)) || !Array.isArray(value.stopConditions) || !value.stopConditions.every(safeStop) || !Array.isArray(value.scores) || value.scores.length > 5 || !(value.scorePercent === null || metric(value.scorePercent))) throw new Error("evidence_write_failed");
  return Object.freeze({ schemaVersion: 1, runId: value.runId, correlationId: value.correlationId, result: value.result, scorePercent: value.scorePercent, scores: Object.freeze(value.scores.map(sanitizeScore)), stopConditions: Object.freeze([...value.stopConditions]), containment: value.containment, reproductionCommand: value.reproductionCommand });
}
function sanitizeScore(score: StructuredOutputValidationEvidence["scores"][number]): StructuredOutputValidationEvidence["scores"][number] {
  const input = score as unknown as Record<string, unknown>; const keys = Object.keys(input).sort(); const expected = ["correctionEffort", "denominator", "falseNegatives", "falsePositives", "governingStateOmissions", "precisionPercent", "provenanceFailures", "recallPercent", "reentryOmissions", "truePositives", "type", "unsupportedClaims"];
  if (keys.length !== expected.length || !keys.every((key, index) => key === expected[index]) || !["fact", "decision", "research", "open_question", "task"].includes(String(input.type)) || !["denominator", "truePositives", "falsePositives", "falseNegatives", "unsupportedClaims", "provenanceFailures", "governingStateOmissions", "reentryOmissions", "correctionEffort"].every((key) => integer(input[key])) || !metric(input.precisionPercent) || !metric(input.recallPercent) || Number(input.denominator) < 1 || Number(input.truePositives) + Number(input.falseNegatives) !== Number(input.denominator)) throw new Error("evidence_write_failed");
  return Object.freeze({ type: input.type as StructuredOutputValidationEvidence["scores"][number]["type"], denominator: input.denominator as number, truePositives: input.truePositives as number, falsePositives: input.falsePositives as number, falseNegatives: input.falseNegatives as number, unsupportedClaims: input.unsupportedClaims as number, provenanceFailures: input.provenanceFailures as number, governingStateOmissions: input.governingStateOmissions as number, reentryOmissions: input.reentryOmissions as number, correctionEffort: input.correctionEffort as number, precisionPercent: input.precisionPercent as number, recallPercent: input.recallPercent as number });
}
function integer(value: unknown): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 0; }
function metric(value: unknown): value is number { return typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 100; }
function safeStop(value: unknown): value is string { return typeof value === "string" && /^[a-z][a-z0-9_]{0,79}$/u.test(value) && !FORBIDDEN.test(value); }
